name: Build & Deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  PROJECT: flow-battleblocks
  REGISTRY: europe-central2-docker.pkg.dev
  IMAGE_NAME: battleblocks-frontend

jobs:
  docker-build:
    name: Docker Build
    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: docker/login-action@v2
        with:
          registry: "europe-central2-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - id: build-and-push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PROJECT }}/docker/${{ env.IMAGE_NAME }}:latest
      - uses: google-github-actions/setup-gcloud@v1
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: cluster-1
          location: europe-central2-a
      - run: |
          kubectl rollout restart deployment/${{ env.IMAGE_NAME }}-service -n bb
          kubectl rollout status deployment/${{ env.IMAGE_NAME }}-service -n bb --timeout 60s
