name: Build & Deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: battleblocks-frontend

jobs:
  docker-build:
    name: Docker Build
    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          create_credentials_file: false
          export_environment_variables: false
      - uses: docker/login-action@v2
        with:
          registry: "europe-central2-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - id: build-and-push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            europe-central2-docker.pkg.dev/flow-battleblocks/docker/$IMAGE_NAME:latest
